#!/bin/bash
#Pasa todas las copias que acaban en .tar.gz a lan
rsync -avz -e "ssh -i /vagrant/.vagrant/machines/lan/virtualbox/private_key" /home/vagrant/backups/*.tar.gz vagrant@192.168.120.2:/home/vagrant/
